#!/bin/bash

# if structure at begginnig of script to confirm that u provided at least one arg on cmd line 
# test -eq operator compares two integers;
# $# special paramter takes on the value of the number of cmd-line argument

if test $# -eq 0         
  then
    echo "You must supply at least one argument."
    exit 1
fi
echo "Program running."